# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a2be89e509d6f51ce955d8eed8771cdae837ab157a91ca26ee2224a753f17b7afa89d773a26f26246a0ae45351ef2da34225b3028796fa2be257aa2bb3cd313

test:
  secret_key_base: 4db8189480b6fea29a0fcbaa54c520c11ff9eb57915b5cc91b6676e35c14f068ef5ca03a9b0517f2b5ee804ad4a50784f4bc936ae86916dc8b8e60d662434b37

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
